# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kunal Patel
description: "Hi, I'm Kunal, a Software Developer with a passion for building impactful and innovative solutions. My portfolio highlights projects that showcase my technical expertise and focus on delivering real business value. Feel free to explore my GitHub and LinkedIn profiles or download my resume using the links below!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Melbourne, Australia"
resume_url: /docs/Kunal_Patel_Resume.docx
avatar_image: /img/passportphoto.JPG

#-------------------------------
# Contact links
linkedln: "www.linkedin.com/in/kunallpatel" # Add your linkedln handle
github: "https://github.com/KunalPatel97"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

